version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - "8000:8000"
    networks:
      - monitoring

  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge