/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119342-g37bd915042-20250423"
#endif /* AVUTIL_FFVERSION_H */
